### ISSUE TITLE
I am having error in this

### ISSUE THREAD

**Issue by nikitasorted** [wandaweb/Fooocus-Sagemaker-Studio-Lab#10]
This is the error: 
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/launch.py", line 132, in <module>
    config.default_base_model_name, config.checkpoint_downloads = download_models(
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/launch.py", line 98, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/model_loader.py", line 24, in load_file_from_url
    from torch.hub import download_url_to_file
ModuleNotFoundError: No module named 'torch'

**Comment by wandaweb** [comment]
Hi, please try using the updated model-management notebook to delete the existing installation by running the last code block and then reinstall Foocus by rynning start.sh

This is an issue caused by an update to the Fooocus app, which deletes the /tmp/fooocus folder, where the conda environment used to be installed.
