### ISSUE TITLE
libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KickOffNo1** [wandaweb/Fooocus-Sagemaker-Studio-Lab#6]
Tried to setup in Code Editor within Sagemaker studio. Installs fine until in the very last step the error messages libGL.so.1: cannot open shared object file: No such file or directory shows up in the terminal. Fooocus is already accessbile in the browser, but never gets beyond "waiting for task to start" when trying to generate an image.

**Comment by wandaweb** [comment]
Hi, I was not able to reproduce this error in Sagemaker Studio Lab. Try running `rm -rf /home/studio-lab-user/.conda/fooocus` to make sure the installer can create the conda environment and run `sh start.sh` from the command line. If you are still getting errors, please paste the console output here and I will do my best to troubleshoot.

**Comment by KickOffNo1** [comment]
Thanks for your response. It works indeed in Sagemaker Studio lab, unfortunately it comes with 15GB of disk space only, which is not sufficient for Fooocus if you want to try out all the functions. I tried it in Sagemaker Studio in a Code Editor space. That's where I got the error messages. 

`Exception in thread Thread-3 (worker):
Traceback (most recent call last):
  File "/home/sagemaker-user/.conda/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sagemaker-user/.conda/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sagemaker-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/async_worker.py", line 31, in worker
    import extras.preprocessors as preprocessors
  File "/home/sagemaker-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/extras/preprocessors.py", line 1, in <module>
    import cv2
  File "/home/sagemaker-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/sagemaker-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/sagemaker-user/.conda/envs/fooocus/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory`
