### ISSUE TITLE
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Darkhydra8788** [wandaweb/Fooocus-Sagemaker-Studio-Lab#7]
notebook was working fine previously, i didn't make any changes in it still i am getting an libgthread import error.
I am providing the full error code.

(studiolab) studio-lab-user@default:~/Fooocus-Sagemaker-Studio-Lab$ sh start.sh
Cloning into 'Fooocus'...
remote: Enumerating objects: 5229, done.
remote: Counting objects: 100% (310/310), done.
remote: Compressing objects: 100% (299/299), done.
remote: Total 5229 (delta 13), reused 295 (delta 7), pack-reused 4919
Receiving objects: 100% (5229/5229), 32.24 MiB | 51.91 MiB/s, done.
Resolving deltas: 100% (3012/3012), done.
Already up to date.
JSON file created: config.txt
Port 7865 is free.
Enter the token: 2bHAgoL3IVYorJS09GLelw6rAy9_2B8LwRf4gGgbp2haTMvFV
Enter the domain: loudly-eminent-cardinal.ngrok-free.app
Token: 2bHAgoL3IVYorJS09GLelw6rAy9_2B8LwRf4gGgbp2haTMvFV
Domain: loudly-eminent-cardinal.ngrok-free.app
https://loudly-eminent-cardinal.ngrok-free.app
Press Ctrl+C to exit
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus/entry_with_update.py', '--always-high-vram']
Traceback (most recent call last):
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/launch.py", line 24, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/config.py", line 7, in <module>
    import modules.sdxl_styles
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/util.py", line 6, in <module>
    import cv2
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
![Screenshot (25)](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/157311981/f293e79a-9496-4f45-872e-b7fa4581ba5b)

**Comment by wallofroy** [comment]
im also facing the same issue... Wanda please help!

**Comment by mrmarkbrown** [comment]
> im also facing the same issue... Wanda please help!

Same
